name: Build WAR with Maven

on:
  push:
    branches:
      - master  # Trigger on push to the main branch (you can change this to any branch)
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can also use 'windows-latest' or 'macos-latest' if needed

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Choose the appropriate Java version (you can use 8, 11, or 17)
        distribution: 'adoptopenjdk'

    - name: Build with Maven
      run: mvn clean package  # This runs 'mvn clean package' to build the WAR file

    - name: Upload WAR file
      uses: actions/upload-artifact@v2
      with:
        name: HelloWorld.war
        path: target/HelloWorld.war  # This uploads the WAR file as an artifact
