name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Gradle/Maven
      run: ./gradlew build # Change to ./mvnw package if using Maven

    - name: Create WAR file
      run: mv build/libs/*.war build/libs/app.war # Adjust path if necessary

    - name: Copy WAR file to server
      uses: appleboy/scp-action@v0.0.1
      with:
        source: "build/libs/app.war"
        target: "Abishek@103.186.40.7:/webapps/"
        port: 20
        strip_components: 1
      env:
        SSH_PASSWORD: ${{ secrets.SFTP_PASS }}
