name: Build and Deploy WAR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          
      - name: Build WAR file
        run: mvn clean package
        
      - name: Upload WAR to server
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 20
          source: ./target/helloworld.war
          target: /webapps/helloworld.war
