name: Build and Deploy WAR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build WAR
      run: ./gradlew build  # or ./mvnw package for Maven

    - name: Copy WAR to Windows Server
      uses: atlassian/ssh-run@v2
      with:
        host: "103.186.40.7"
        username: "Abishek"
        password: ${{ secrets.SFTP_PASS }}
        script: |
          mkdir -p C:\webapps
          copy build/libs/*.war C:\webapps\
